# Generated by Django 4.2.13 on 2026-07-03 05:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=14, unique=True)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=10)),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('contribution_tier', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('savings_goal', models.CharField(blank=True, choices=[('LAND', 'Land'), ('CAR', 'Car'), ('HOUSE', 'House'), ('BUSINESS', 'Business Capital'), ('SCHOOL_FEES', 'School Fees'), ('FLEXIBLE', 'Flexible')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('GRACE_PERIOD', 'Grace Period'), ('SUSPENDED', 'Suspended'), ('GRADUATED', 'Graduated'), ('WAITLISTED', 'Waitlisted')], default='ACTIVE', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'members',
                'ordering': ['-joined_at'],
            },
        ),
    ]
