# Generated by Django 4.2.13 on 2026-07-03 05:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('month_year', models.CharField(max_length=7)),
                ('deduction_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='PENDING', max_length=20)),
                ('transaction_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('method', models.CharField(choices=[('STANDING_ORDER', 'Standing Order'), ('MANUAL', 'Manual'), ('USSD', 'USSD')], default='STANDING_ORDER', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'contributions',
                'ordering': ['-created_at'],
            },
        ),
    ]
