# Generated by Django 4.2.13 on 2026-07-03 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Waitlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('goal_type', models.CharField(max_length=20)),
                ('contribution_tier', models.DecimalField(decimal_places=2, max_digits=12)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('priority', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('PROMOTED', 'Promoted to Group'), ('CANCELLED', 'Cancelled')], default='WAITING', max_length=20)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'waitlist',
                'ordering': ['priority'],
            },
        ),
    ]
