# Generated by Django 4.2.13 on 2026-07-03 05:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('goal_type', models.CharField(choices=[('LAND', 'Land'), ('CAR', 'Car'), ('HOUSE', 'House'), ('BUSINESS', 'Business Capital'), ('SCHOOL_FEES', 'School Fees'), ('FLEXIBLE', 'Flexible')], max_length=20)),
                ('contribution_tier', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_members', models.PositiveIntegerField(default=6)),
                ('current_cycle_month', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('FORMING', 'Forming'), ('ACTIVE', 'Active'), ('COMPLETE', 'Complete'), ('SUSPENDED', 'Suspended')], default='FORMING', max_length=20)),
                ('reserve_fund', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('rotation_order', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'savings_groups',
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rotation_position', models.PositiveIntegerField()),
                ('has_collected', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='groups.savingsgroup')),
            ],
            options={
                'db_table': 'group_memberships',
                'ordering': ['rotation_position'],
            },
        ),
    ]
