# Generated by Django 4.2.13 on 2026-07-03 05:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceCover',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='AXA Mansard', max_length=100)),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLAIMED', 'Claimed'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('claim_status', models.CharField(choices=[('NONE', 'No Claim'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='NONE', max_length=20)),
                ('claim_reason', models.CharField(blank=True, choices=[('DEATH', 'Death'), ('JOB_LOSS', 'Job Loss')], max_length=20, null=True)),
                ('claim_date', models.DateField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insurance_covers', to='groups.savingsgroup')),
            ],
            options={
                'db_table': 'insurance_covers',
            },
        ),
    ]
