# Generated by Django 4.2.13 on 2026-07-03 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notif_type', models.CharField(choices=[('DEDUCTION', 'Contribution Deducted'), ('GROUP_UPDATE', 'Group Update'), ('POT_MONTH', 'Pot Month'), ('INSURANCE', 'Insurance Update'), ('SYSTEM', 'System')], max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('channel', models.CharField(choices=[('IN_APP', 'In App'), ('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp')], default='IN_APP', max_length=20)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-sent_at'],
            },
        ),
    ]
